services:
  db:
    image: postgres:18-alpine
    container_name: bookme-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - bookme-network

  backend:
    image: braxon2/bookme-backend:latest
    container_name: bookmeci-cd-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      aws.s3.bucketName: ${AWS_S3_BUCKET_NAME}
      aws.s3.region: ${AWS_S3_REGION}
      aws.accessKeyId: ${AWS_ACCESS_KEY_ID}
      aws.secretKey: ${AWS_SECRET_ACCESS_KEY}
      ratingLimit.tokenInBucket: ${RATINGLIMIT_TOKENINBUCKET}
      ratingLimit.duration: ${RATINGLIMIT_DURATION}
    networks:
      - bookme-network

  frontend:
    image: braxon2/bookme-frontend:latest
    container_name: bookme-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - bookme-network

volumes:
  postgres_data:

networks:
  bookme-network:
    driver: bridge
