CREATE TABLE public.addon_mapping (
    id bigint NOT NULL,
    per_night boolean NOT NULL,
    addon_id bigint,
    unit_id bigint
);

ALTER TABLE public.addon_mapping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addon_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.addon_mapping
    ADD CONSTRAINT addon_mapping_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.addon_mapping
    ADD CONSTRAINT fk_addon_mapping_addon FOREIGN KEY (addon_id) REFERENCES public.addon(id);

ALTER TABLE ONLY public.addon_mapping
    ADD CONSTRAINT fk_addon_mapping_unit FOREIGN KEY (unit_id) REFERENCES public.bookable_unit(id);

-- Migrate existing data from Addon to AddonMapping
-- This ensures you don't lose the existing connections between units and addons
INSERT INTO public.addon_mapping (per_night, addon_id, unit_id)
SELECT per_night, id, unit_id FROM public.addon;

-- Update period_price_addon to point to the new mapping table
-- First, drop the old foreign key constraint pointing to the addon table
ALTER TABLE public.period_price_addon DROP CONSTRAINT fk4blf7g4mo8qptstxdygej600e;

-- Rename the column so it correctly identifies what it points to
ALTER TABLE public.period_price_addon RENAME COLUMN addon_id TO addon_mapping_id;

-- (Data Migration for period_price_addon)
-- If you have existing data in period_price_addon, map the old addon_id to the new addon_mapping_id
UPDATE public.period_price_addon ppa
SET addon_mapping_id = am.id
    FROM public.addon_mapping am
WHERE ppa.addon_mapping_id = am.addon_id;

-- Add the new foreign key constraint pointing to addon_mapping
ALTER TABLE ONLY public.period_price_addon
    ADD CONSTRAINT fk_period_price_addon_mapping FOREIGN KEY (addon_mapping_id) REFERENCES public.addon_mapping(id);

-- Clean up the original addon table
-- Drop the old unit_id foreign key constraint
ALTER TABLE public.addon DROP CONSTRAINT fkii7vy8ug5ki0a4bwcio18dsmf;

-- Remove the columns that have been moved to addon_mapping
ALTER TABLE public.addon DROP COLUMN per_night;
ALTER TABLE public.addon DROP COLUMN unit_id;