CREATE TABLE public.booking_addon_item (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    booking_id bigint NOT NULL,
    addon_id bigint NOT NULL,
    price_paid double precision NOT NULL,
    was_per_night boolean NOT NULL,
    CONSTRAINT booking_addon_item_pkey PRIMARY KEY (id),
    CONSTRAINT fk_booking_addon_item_booking FOREIGN KEY (booking_id) REFERENCES public.booking(id),
    CONSTRAINT fk_booking_addon_item_addon FOREIGN KEY (addon_id) REFERENCES public.addon(id)
);